################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_cbc.c \
../STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_ccm.c \
../STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_cfb.c \
../STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_ctr.c \
../STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_ecb.c \
../STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_gcm.c \
../STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_keywrap.c \
../STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_ofb.c \
../STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_xts.c \
../STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_chachapoly.c 

OBJS += \
./STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_cbc.o \
./STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_ccm.o \
./STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_cfb.o \
./STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_ctr.o \
./STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_ecb.o \
./STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_gcm.o \
./STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_keywrap.o \
./STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_ofb.o \
./STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_xts.o \
./STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_chachapoly.o 

C_DEPS += \
./STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_cbc.d \
./STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_ccm.d \
./STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_cfb.d \
./STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_ctr.d \
./STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_ecb.d \
./STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_gcm.d \
./STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_keywrap.d \
./STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_ofb.d \
./STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_xts.d \
./STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_chachapoly.d 


# Each subdirectory must supply rules for building sources it contributes
STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_cbc.o: ../STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_cbc.c STM32_Cryptographic/legacy_v3/src/cipher/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/STM32_Cryptographic/include" -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/STM32_Cryptographic/include/cipher" -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/STM32_Cryptographic/legacy_v3/include" -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/STM32_Cryptographic/legacy_v3/include/cipher" -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/DCM/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_cbc.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_ccm.o: ../STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_ccm.c STM32_Cryptographic/legacy_v3/src/cipher/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/STM32_Cryptographic/include" -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/STM32_Cryptographic/include/cipher" -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/STM32_Cryptographic/legacy_v3/include" -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/STM32_Cryptographic/legacy_v3/include/cipher" -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/DCM/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_ccm.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_cfb.o: ../STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_cfb.c STM32_Cryptographic/legacy_v3/src/cipher/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/STM32_Cryptographic/include" -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/STM32_Cryptographic/include/cipher" -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/STM32_Cryptographic/legacy_v3/include" -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/STM32_Cryptographic/legacy_v3/include/cipher" -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/DCM/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_cfb.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_ctr.o: ../STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_ctr.c STM32_Cryptographic/legacy_v3/src/cipher/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/STM32_Cryptographic/include" -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/STM32_Cryptographic/include/cipher" -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/STM32_Cryptographic/legacy_v3/include" -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/STM32_Cryptographic/legacy_v3/include/cipher" -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/DCM/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_ctr.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_ecb.o: ../STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_ecb.c STM32_Cryptographic/legacy_v3/src/cipher/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/STM32_Cryptographic/include" -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/STM32_Cryptographic/include/cipher" -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/STM32_Cryptographic/legacy_v3/include" -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/STM32_Cryptographic/legacy_v3/include/cipher" -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/DCM/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_ecb.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_gcm.o: ../STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_gcm.c STM32_Cryptographic/legacy_v3/src/cipher/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/STM32_Cryptographic/include" -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/STM32_Cryptographic/include/cipher" -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/STM32_Cryptographic/legacy_v3/include" -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/STM32_Cryptographic/legacy_v3/include/cipher" -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/DCM/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_gcm.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_keywrap.o: ../STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_keywrap.c STM32_Cryptographic/legacy_v3/src/cipher/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/STM32_Cryptographic/include" -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/STM32_Cryptographic/include/cipher" -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/STM32_Cryptographic/legacy_v3/include" -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/STM32_Cryptographic/legacy_v3/include/cipher" -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/DCM/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_keywrap.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_ofb.o: ../STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_ofb.c STM32_Cryptographic/legacy_v3/src/cipher/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/STM32_Cryptographic/include" -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/STM32_Cryptographic/include/cipher" -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/STM32_Cryptographic/legacy_v3/include" -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/STM32_Cryptographic/legacy_v3/include/cipher" -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/DCM/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_ofb.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_xts.o: ../STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_xts.c STM32_Cryptographic/legacy_v3/src/cipher/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/STM32_Cryptographic/include" -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/STM32_Cryptographic/include/cipher" -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/STM32_Cryptographic/legacy_v3/include" -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/STM32_Cryptographic/legacy_v3/include/cipher" -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/DCM/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_aes_xts.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_chachapoly.o: ../STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_chachapoly.c STM32_Cryptographic/legacy_v3/src/cipher/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/STM32_Cryptographic/include" -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/STM32_Cryptographic/include/cipher" -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/STM32_Cryptographic/legacy_v3/include" -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/STM32_Cryptographic/legacy_v3/include/cipher" -I"C:/Users/HP/Documents/work_space/SIGMA_UDS_TP/DCM/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32_Cryptographic/legacy_v3/src/cipher/legacy_v3_chachapoly.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

